.TH "Emotions Directory Reference" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emotions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Anger\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Contempt\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Disgust\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Fear\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Joy\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Sadness\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Surprise\&.cs\fP"
.br
.in -1c
