.TH "Framework/Model.cs" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Framework/Model.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRealSense\&.Model\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRealSense\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
