.TH "RealSense.FriggnAweseomeGraphix.MEMonitor" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.FriggnAweseomeGraphix.MEMonitor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMEMonitor\fP (String majText, String minText, int xP, int yP, int rad, int thick)"
.br
.ti -1c
.RI "void \fBStep\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBradius\fP"
.br
.ti -1c
.RI "int \fBthickness\fP"
.br
.ti -1c
.RI "int \fBcurrentValue\fP = 0"
.br
.ti -1c
.RI "int \fBtargetValue\fP = 0"
.br
.ti -1c
.RI "String \fBmajorText\fP"
.br
.ti -1c
.RI "String \fBminorText\fP"
.br
.ti -1c
.RI "bool \fBshowPercent\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Custom UI-Component to stylishly display percentage-values 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.MEMonitor (String majText, String minText, int xP, int yP, int rad, int thick)"
Init component 
.PP
\fBParameters:\fP
.RS 4
\fIString\fP majText - main text 
.br
\fIString\fP minText - additional Text 
.br
\fIint\fP xP - x-coordinate 
.br
\fIint\fP yP - y-coordinate 
.br
\fIint\fP rad - radius 
.br
\fIint\fP thick - thickness 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.Step ()"
Interpolate to the target-value (for fluid transitions) 
.SH "Member Data Documentation"
.PP 
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.currentValue = 0"

.SS "String RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.majorText"

.SS "String RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.minorText"

.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.radius"

.SS "bool RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.showPercent = true"

.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.targetValue = 0"

.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.thickness"

.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.x"

.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
