.TH "RealSense.AU_LipLine" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.AU_LipLine
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAU_LipLine\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Measures how accurate the lip-landmark-points are on one line and stores its' value inside the model\&. 
.PP
\fBAuthor:\fP
.RS 4
David  Hufflepuff
.RE
.PP
Interpretation: -100 = Saaaaaad 0 = Relaxed 100 = Grinning 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.AU_LipLine\&.AU_LipLine ()"
Initializes the AU by setting up the default value boundaries\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.AU_LipLine\&.Work (Graphics g)\fC [virtual]\fP"
Calculates whether or not all LipPoints are placed on one line over a set number of frames and prints its' debug-message to the \fBCameraView\fP when debug is enabled\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
