.TH "RealSense.EM_Anger" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.EM_Anger
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEM_Anger\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file EM_Anger\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.EM_Anger\&.EM_Anger ()"
Initializes the EM, setting the debug-flag to true by default 
.PP
Definition at line 21 of file EM_Anger\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.EM_Anger\&.Work (Graphics g)\fC [virtual]\fP"
Computes the percentage Value of Anger in the current Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.
.PP
Definition at line 31 of file EM_Anger\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
