.TH "RealSense.AU_UpperLipRaised" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.AU_UpperLipRaised
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAU_UpperLipRaised\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Measures whether or not the upper lip is raised and stores its' value inside the model\&. 
.PP
\fBAuthor:\fP
.RS 4
Tobias Schramm  Hufflepuff
.RE
.PP
Interpretation: 0 = Relaxed 100 = Lip up 
.PP
Definition at line 18 of file AU_UpperLipRaised\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.AU_UpperLipRaised\&.AU_UpperLipRaised ()"
Initializes the AU by setting up the default value boundaries\&. 
.PP
Definition at line 30 of file AU_UpperLipRaised\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.AU_UpperLipRaised\&.Work (Graphics g)\fC [virtual]\fP"
Calculates the average difference between the upper lip and the nose to measure in which direction (and how far) it was moved over a set number of frames and prints its' debug-message to the \fBCameraView\fP when debug is enabled\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.
.PP
Definition at line 48 of file AU_UpperLipRaised\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
