.TH "RealSense.Program" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Program
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This ist the main class\&. It starts the model and adds all modules to our \fBModel\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Tanja Witke, David Rosenbusch 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
