.TH "RealSense.LandmarkGroupModule" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.LandmarkGroupModule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Module to display Landmark-Points by their groups, as they are defined in the SDK 
.PP
\fBAuthor:\fP
.RS 4
: David Rosenbusch 
.PP
: Tobias Schramm  Hufflepuff 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.LandmarkGroupModule\&.Work (Graphics g)\fC [virtual]\fP"
Displays Landmarks by group, as they are defined in the SDK 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
