.TH "RealSense.ME_BearTeeth" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.ME_BearTeeth
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBME_BearTeeth\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.ME_BearTeeth\&.ME_BearTeeth ()"
Sets default-values 
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.ME_BearTeeth\&.Work (Graphics g)\fC [virtual]\fP"
Calculates the difference between the two lip corners 
.PP
Implements \fBRealSense\&.RSModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
