.TH "RealSense.Emotions.EM_Sadness" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Emotions.EM_Sadness
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEM_Sadness\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Measures the percentage value of sadness\&. 
.PP
\fBAuthor:\fP
.RS 4
Tanja 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.Emotions\&.EM_Sadness\&.EM_Sadness ()"
Initializes the EM, setting the debug-flag to true by default 
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.Emotions\&.EM_Sadness\&.Work (Graphics g)\fC [virtual]\fP"
Computes the percentage Value of Sadness in the current Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
