.TH "RealSense.Emotions.EM_Fear" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Emotions.EM_Fear
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEM_Fear\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file EM_Fear\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.Emotions\&.EM_Fear\&.EM_Fear ()"
Initializes the EM, setting the debug-flag to true by default 
.PP
Definition at line 19 of file EM_Fear\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.Emotions\&.EM_Fear\&.Work (Graphics g)\fC [virtual]\fP"
Computes the percentage Value of fear in the current Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.
.PP
Definition at line 28 of file EM_Fear\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
