.TH "RealSense.Emotions" 3 "Thu Jul 20 2017" "Version 0.7.8.21" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Emotions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEM_Contempt\fP"
.br
.ti -1c
.RI "class \fBEM_Disgust\fP"
.br
.ti -1c
.RI "class \fBEM_Fear\fP"
.br
.ti -1c
.RI "class \fBEM_Joy\fP"
.br
.ti -1c
.RI "class \fBEM_Sadness\fP"
.br
.ti -1c
.RI "class \fBEM_Surprise\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
