.TH "C:/Users/nutzer/Documents/GitHub/RealSense/Emotions/AssemblyInfo.cs" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nutzer/Documents/GitHub/RealSense/Emotions/AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
