.TH "C:/Users/nutzer/Documents/GitHub/RealSense/ActionUnits/AU_EyelidTight.cs" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nutzer/Documents/GitHub/RealSense/ActionUnits/AU_EyelidTight.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRealSense\&.AU_EyelidTight\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRealSense\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
