.TH "C:/Users/nutzer/Documents/GitHub/RealSense/Emotions Directory Reference" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nutzer/Documents/GitHub/RealSense/Emotions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Anger\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Contempt\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Disgust\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Fear\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Joy\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Sadness\&.cs\fP"
.br
.ti -1c
.RI "file \fBEM_Surprise\&.cs\fP"
.br
.in -1c
