.TH "C:/Users/nutzer/Documents/GitHub/RealSense/ActionUnits Directory Reference" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nutzer/Documents/GitHub/RealSense/ActionUnits Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAU_BrowShift\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_EyelidTight\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_JawDrop\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_LipCorner\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_LipLine\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_LipsTightened\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_LipStretched\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_LowerLipLowered\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_LowerLipRaised\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_NoseWrinkled\&.cs\fP"
.br
.ti -1c
.RI "file \fBAU_UpperLipRaised\&.cs\fP"
.br
.in -1c
