.TH "C:/Users/nutzer/Documents/GitHub/RealSense/Various Directory Reference" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nutzer/Documents/GitHub/RealSense/Various Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFaceRect\&.cs\fP"
.br
.ti -1c
.RI "file \fBFaceTrackerModule\&.cs\fP"
.br
.ti -1c
.RI "file \fBGauge_Module\&.cs\fP"
.br
.ti -1c
.RI "file \fBLandmarkGroupModule\&.cs\fP"
.br
.ti -1c
.RI "file \fBLandmarkTypeModule\&.cs\fP"
.br
.ti -1c
.RI "file \fBME_BearTeeth\&.cs\fP"
.br
.in -1c
