.TH "Analyse Directory Reference" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Analyse Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAnalyzerView\&.cs\fP"
.br
.ti -1c
.RI "file \fBFaceRecorder\&.cs\fP"
.br
.ti -1c
.RI "file \fBFaceRecording\&.cs\fP"
.br
.in -1c
