.TH "RealSense.CameraView" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.CameraView
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraView\fP (\fBModel\fP model, bool test)"
.br
.ti -1c
.RI "void \fBAddComponent\fP (Control c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsave\fP = 0"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBDebug_Y\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Boolean \fBResetModules\fP\fC [set]\fP"
.br
.ti -1c
.RI "Bitmap \fBColorBitmap\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file CameraView\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.CameraView\&.CameraView (\fBModel\fP model, bool test)"
Initialise View and start updater Thread 
.PP
Definition at line 67 of file CameraView\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void RealSense\&.CameraView\&.AddComponent (Control c)"

.PP
Definition at line 203 of file CameraView\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int RealSense\&.CameraView\&.save = 0"

.PP
Definition at line 31 of file CameraView\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Bitmap RealSense\&.CameraView\&.ColorBitmap\fC [get]\fP"

.PP
Definition at line 465 of file CameraView\&.cs\&.
.SS "int RealSense\&.CameraView\&.Debug_Y\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 449 of file CameraView\&.cs\&.
.SS "Boolean RealSense\&.CameraView\&.ResetModules\fC [set]\fP"

.PP
Definition at line 455 of file CameraView\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
