.TH "RealSense" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEmotions\fP"
.br
.ti -1c
.RI "namespace \fBProperties\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnalyzerView\fP"
.br
.ti -1c
.RI "class \fBCameraView\fP"
.br
.ti -1c
.RI "class \fBEM_Anger\fP"
.br
.ti -1c
.RI "class \fBEmotionSaver\fP"
.br
.ti -1c
.RI "class \fBEmotionView\fP"
.br
.ti -1c
.RI "class \fBFaceRecorder\fP"
.br
.ti -1c
.RI "class \fBFaceRecording\fP"
.br
.ti -1c
.RI "class \fBFaceRect\fP"
.br
.ti -1c
.RI "class \fBFaceTrackerModule\fP"
.br
.ti -1c
.RI "class \fBFriggnAweseomeGraphix\fP"
.br
.ti -1c
.RI "class \fBGauge_Module\fP"
.br
.ti -1c
.RI "class \fBLandmarkGroupModule\fP"
.br
.ti -1c
.RI "class \fBLandmarkTypeModule\fP"
.br
.ti -1c
.RI "class \fBME_BearTeeth\fP"
.br
.ti -1c
.RI "class \fBME_BrowShift\fP"
.br
.ti -1c
.RI "class \fBME_EyelidTight\fP"
.br
.ti -1c
.RI "class \fBME_JawDrop\fP"
.br
.ti -1c
.RI "class \fBME_LipCorner\fP"
.br
.ti -1c
.RI "class \fBME_LipLine\fP"
.br
.ti -1c
.RI "class \fBME_LipsTightened\fP"
.br
.ti -1c
.RI "class \fBME_LipStretched\fP"
.br
.ti -1c
.RI "class \fBME_LowerLipLowered\fP"
.br
.ti -1c
.RI "class \fBME_LowerLipRaised\fP"
.br
.ti -1c
.RI "class \fBME_NoseWrinkled\fP"
.br
.ti -1c
.RI "class \fBME_UpperLipRaised\fP"
.br
.ti -1c
.RI "class \fBModel\fP"
.br
.ti -1c
.RI "class \fBMultiFormContext\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBRSModule\fP"
.br
.ti -1c
.RI "class \fBUtilities\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
You´re supposed to make some comments! Otherwise I´m going to kill you! :)
.PP
\fBAuthor:\fP
.RS 4
: David Rosenbusch
.PP
: Tobi 
.PP
: 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
