.TH "RealSense.MultiFormContext" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.MultiFormContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApplicationContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiFormContext\fP (params Form[] forms)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file MultiFormContext\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.MultiFormContext\&.MultiFormContext (params Form [] forms)"

.PP
Definition at line 9 of file MultiFormContext\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
