.TH "RealSense.FaceRect" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.FaceRect
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Draws a rectangle, sorrounding the subject's face 
.PP
\fBAuthor:\fP
.RS 4
: David Rosenbusch  Hufflepuff 
.RE
.PP

.PP
Definition at line 15 of file FaceRect\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.FaceRect\&.Work (Graphics g)\fC [virtual]\fP"
Draws a rectangle\&.\&.\&. wow 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.
.PP
Definition at line 23 of file FaceRect\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
