.TH "RealSense.FriggnAweseomeGraphix.MEMonitor" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.FriggnAweseomeGraphix.MEMonitor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMEMonitor\fP (String majText, String minText, int xP, int yP, int rad, int thick)"
.br
.ti -1c
.RI "void \fBstep\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBradius\fP"
.br
.ti -1c
.RI "int \fBthickness\fP"
.br
.ti -1c
.RI "int \fBcurrentValue\fP = 0"
.br
.ti -1c
.RI "int \fBtargetValue\fP = 0"
.br
.ti -1c
.RI "String \fBmajorText\fP"
.br
.ti -1c
.RI "String \fBminorText\fP"
.br
.ti -1c
.RI "bool \fBshowPercent\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file FriggnAweseomeGraphix\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.MEMonitor (String majText, String minText, int xP, int yP, int rad, int thick)"

.PP
Definition at line 45 of file FriggnAweseomeGraphix\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.step ()"

.PP
Definition at line 55 of file FriggnAweseomeGraphix\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.currentValue = 0"

.PP
Definition at line 39 of file FriggnAweseomeGraphix\&.cs\&.
.SS "String RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.majorText"

.PP
Definition at line 41 of file FriggnAweseomeGraphix\&.cs\&.
.SS "String RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.minorText"

.PP
Definition at line 42 of file FriggnAweseomeGraphix\&.cs\&.
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.radius"

.PP
Definition at line 37 of file FriggnAweseomeGraphix\&.cs\&.
.SS "bool RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.showPercent = true"

.PP
Definition at line 43 of file FriggnAweseomeGraphix\&.cs\&.
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.targetValue = 0"

.PP
Definition at line 40 of file FriggnAweseomeGraphix\&.cs\&.
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.thickness"

.PP
Definition at line 38 of file FriggnAweseomeGraphix\&.cs\&.
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.x"

.PP
Definition at line 35 of file FriggnAweseomeGraphix\&.cs\&.
.SS "int RealSense\&.FriggnAweseomeGraphix\&.MEMonitor\&.y"

.PP
Definition at line 36 of file FriggnAweseomeGraphix\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
