.TH "RealSense.AnalyzerView" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.AnalyzerView
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnalyzerView\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file AnalyzerView\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.AnalyzerView\&.AnalyzerView ()"

.PP
Definition at line 52 of file AnalyzerView\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
