.TH "RealSense.Program" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Program
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This ist the main class\&. It starts the model and adds all modules to our \fBModel\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Tanja Witke, David Rosenbusch 
.RE
.PP

.PP
Definition at line 21 of file Program\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
