.TH "RealSense.FaceTrackerModule" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.FaceTrackerModule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaceTrackerModule\fP (int[] idx)"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Displays the landmark-points of the current subject within the UI 
.PP
\fBAuthor:\fP
.RS 4
: Tobias Schramm  Hufflepuff 
.RE
.PP

.PP
Definition at line 13 of file FaceTrackerModule\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.FaceTrackerModule\&.FaceTrackerModule (int [] idx)"
Specifies which indexes to display 
.PP
Definition at line 24 of file FaceTrackerModule\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.FaceTrackerModule\&.Work (Graphics g)\fC [virtual]\fP"
Displays landmark-points (all if none were specified) 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for drawing inside the containing UI 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.
.PP
Definition at line 33 of file FaceTrackerModule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
