.TH "RealSense.FaceRecording" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.FaceRecording
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaceRecording\fP (String emotionName)"
.br
.ti -1c
.RI "void \fBsetData\fP (PXCMFaceData\&.LandmarkPoint[][] d, PXCMFaceData\&.LandmarkPoint[] nd)"
.br
.ti -1c
.RI "void \fBsave\fP ()"
.br
.ti -1c
.RI "PXCMFaceData\&.LandmarkPoint [] \fBgetFace\fP (int frame)"
.br
.ti -1c
.RI "PXCMFaceData\&.LandmarkPoint [] \fBgetNullFace\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFaceRecording\fP \fBload\fP (String n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file FaceRecording\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.FaceRecording\&.FaceRecording (String emotionName)"

.PP
Definition at line 17 of file FaceRecording\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "PXCMFaceData\&.LandmarkPoint [] RealSense\&.FaceRecording\&.getFace (int frame)"

.PP
Definition at line 41 of file FaceRecording\&.cs\&.
.SS "PXCMFaceData\&.LandmarkPoint [] RealSense\&.FaceRecording\&.getNullFace ()"

.PP
Definition at line 46 of file FaceRecording\&.cs\&.
.SS "static \fBFaceRecording\fP RealSense\&.FaceRecording\&.load (String n)\fC [static]\fP"

.PP
Definition at line 35 of file FaceRecording\&.cs\&.
.SS "void RealSense\&.FaceRecording\&.save ()"

.PP
Definition at line 28 of file FaceRecording\&.cs\&.
.SS "void RealSense\&.FaceRecording\&.setData (PXCMFaceData\&.LandmarkPoint d[][], PXCMFaceData\&.LandmarkPoint [] nd)"

.PP
Definition at line 22 of file FaceRecording\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
