.TH "RealSense.EmotionView" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.EmotionView
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmotionView\fP (\fBModel\fP model)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file EmotionView\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.EmotionView\&.EmotionView (\fBModel\fP model)"

.PP
Definition at line 17 of file EmotionView\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.EmotionView\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 17 of file EmotionView\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
