.TH "RealSense.Properties" 3 "Fri Jul 21 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Properties
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "A strongly-typed resource class, for looking up localized strings, etc\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
