.TH "RealSense.Emotions.EM_Disgust" 3 "Wed Jul 5 2017" "Face Interpreter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSense.Emotions.EM_Disgust
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealSense\&.RSModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEM_Disgust\fP ()"
.br
.ti -1c
.RI "override void \fBWork\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file EM_Disgust\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RealSense\&.Emotions\&.EM_Disgust\&.EM_Disgust ()"

.PP
Definition at line 19 of file EM_Disgust\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RealSense\&.Emotions\&.EM_Disgust\&.Work (Graphics g)\fC [virtual]\fP"
Computes the percentage Value of Disgust in the current Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGraphics\fP g for the view 
.RE
.PP

.PP
Implements \fBRealSense\&.RSModule\fP\&.
.PP
Definition at line 28 of file EM_Disgust\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Face Interpreter from the source code\&.
