var namespace_real_sense =
[
    [ "Emotions", "namespace_real_sense_1_1_emotions.html", "namespace_real_sense_1_1_emotions" ],
    [ "AnalyzerView", "class_real_sense_1_1_analyzer_view.html", "class_real_sense_1_1_analyzer_view" ],
    [ "AU_BrowShift", "class_real_sense_1_1_a_u___brow_shift.html", "class_real_sense_1_1_a_u___brow_shift" ],
    [ "AU_EyelidTight", "class_real_sense_1_1_a_u___eyelid_tight.html", "class_real_sense_1_1_a_u___eyelid_tight" ],
    [ "AU_JawDrop", "class_real_sense_1_1_a_u___jaw_drop.html", "class_real_sense_1_1_a_u___jaw_drop" ],
    [ "AU_LipCorner", "class_real_sense_1_1_a_u___lip_corner.html", "class_real_sense_1_1_a_u___lip_corner" ],
    [ "AU_LipLine", "class_real_sense_1_1_a_u___lip_line.html", "class_real_sense_1_1_a_u___lip_line" ],
    [ "AU_LipsTightened", "class_real_sense_1_1_a_u___lips_tightened.html", "class_real_sense_1_1_a_u___lips_tightened" ],
    [ "AU_LipStretched", "class_real_sense_1_1_a_u___lip_stretched.html", "class_real_sense_1_1_a_u___lip_stretched" ],
    [ "AU_LowerLipLowered", "class_real_sense_1_1_a_u___lower_lip_lowered.html", "class_real_sense_1_1_a_u___lower_lip_lowered" ],
    [ "AU_LowerLipRaised", "class_real_sense_1_1_a_u___lower_lip_raised.html", "class_real_sense_1_1_a_u___lower_lip_raised" ],
    [ "AU_NoseWrinkled", "class_real_sense_1_1_a_u___nose_wrinkled.html", "class_real_sense_1_1_a_u___nose_wrinkled" ],
    [ "AU_UpperLipRaised", "class_real_sense_1_1_a_u___upper_lip_raised.html", "class_real_sense_1_1_a_u___upper_lip_raised" ],
    [ "CameraView", "class_real_sense_1_1_camera_view.html", "class_real_sense_1_1_camera_view" ],
    [ "EM_Anger", "class_real_sense_1_1_e_m___anger.html", "class_real_sense_1_1_e_m___anger" ],
    [ "FaceRecorder", "class_real_sense_1_1_face_recorder.html", "class_real_sense_1_1_face_recorder" ],
    [ "FaceRecording", "class_real_sense_1_1_face_recording.html", "class_real_sense_1_1_face_recording" ],
    [ "FaceRect", "class_real_sense_1_1_face_rect.html", "class_real_sense_1_1_face_rect" ],
    [ "FaceTrackerModule", "class_real_sense_1_1_face_tracker_module.html", "class_real_sense_1_1_face_tracker_module" ],
    [ "FriggnAweseomeGraphix", "class_real_sense_1_1_friggn_aweseome_graphix.html", "class_real_sense_1_1_friggn_aweseome_graphix" ],
    [ "Gauge_Module", "class_real_sense_1_1_gauge___module.html", "class_real_sense_1_1_gauge___module" ],
    [ "LandmarkGroupModule", "class_real_sense_1_1_landmark_group_module.html", "class_real_sense_1_1_landmark_group_module" ],
    [ "LandmarkTypeModule", "class_real_sense_1_1_landmark_type_module.html", "class_real_sense_1_1_landmark_type_module" ],
    [ "ME_BearTeeth", "class_real_sense_1_1_m_e___bear_teeth.html", "class_real_sense_1_1_m_e___bear_teeth" ],
    [ "Model", "class_real_sense_1_1_model.html", "class_real_sense_1_1_model" ],
    [ "Program", "class_real_sense_1_1_program.html", null ],
    [ "RSModule", "class_real_sense_1_1_r_s_module.html", "class_real_sense_1_1_r_s_module" ]
];